### ISSUE TITLE
When building an Ionic solution, the android build fails stating it has duplicate classes

### ISSUE THREAD

**Issue by TonDekker** [wrobins/cordova-plugin-msal#9]
Hi,

I've tried to integrate your plugin in a small test project, and when creating an android build it fails with the following message: 

`* What went wrong:
Execution failed for task ':app:transformDexArchiveWithExternalLibsDexMergerForDebug'. > com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives:
 Program type already present: com.nimbusds.jose.AlgorithmFamily
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.`

I tried to skip the line in the build.gradle so it doesn't copy the 'nimbus-jose-jwt' library during build, but I suspect this is required in order for the msal plugin to function?

Any help would be much appreciated.

**Comment by wrobins** [comment]
Hello!

I bet your issue is that my initial release had a statically compiled .jar version of com.jimbusds.jose.jwt which it was told to build in Gradle. I suggest trying to pull the latest version of this plugin which I released today @2.0.0 and see if it fixes your issue, since it has no binary blob dependencies.

One issue you may encounter, depending on your version of cordova and cordova-android, may be that it complains about other types of conflicting dependencies because of androidx. If you get anything like that, try also installing the androidx adapter plugins per [this guide](https://forum.ionicframework.com/t/migrating-ionic-app-to-androidx/160844) and see if you have any luck there.
<pre>
cordova plugin add cordova-plugin-androidx
cordova plugin add cordova-plugin-androidx-adapter
</pre>

Thanks for your feedback and let me know if this gets it to build for you!

**Comment by TonDekker** [comment]
Thanks for the update. Android build succeeds (after adding the plugins you mentioned).

Now let's see if Ican get it to work :D

**Comment by navjotsrmtpl** [comment]
thanx it worked
